### PR TITLE
Fixed email verification issue

### LINKED ISSUE #1373: Email verification on new user registration
### Directorist version

v7.4.6

### Environment

_No response_

### Description

https://wordpress.org/support/topic/not-gdpr-compliant-not-for-business-paid/

### Steps to reproduce

https://wordpress.org/support/topic/not-gdpr-compliant-not-for-business-paid/

### Isolating the problem

- [X] I have reproduced this bug in localhost.
- [X] This bug happens with a default WordPress theme active (eg. 2021, 2022 etc).

### PR DESCRIPTION
**Pull request by mdalaminbey**
## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [x] New Feature
- [x] Improvement

## ChangeLog

1. Added mail verification feature
2. Create `directorist_password_reset_url()`
3. Create `==CONFIRM_EMAIL_ADDRESS_URL==` And `==SET_PASSWORD_AND_CONFIRM_EMAIL_ADDRESS_URL==`
4. Use a dynamic error message instead of the hard-coded message inside the login feature
5. Remove the URL params from the login page to avoid showing the message `again` and `again`
6. Separate the password reset form From the login file
7. Added reset password frontend validation
8. removed some unneeded `wp_kses_post`

### CODE REVIEW

File: includes/classes/class-email.php [hunk 1]
```diff
@@ -107,6 +107,24 @@ public function replace_in_content( $content, $order_id = 0, $listing_id = 0, $u
 			$order_receipt_link = ATBDP_Permalink::get_payment_receipt_page_link( $order_id );
 			$cats = wp_get_object_terms( $listing_id, ATBDP_CATEGORY, array( 'fields' => 'names' ) );/*@todo, maybe we can use get_the_terms() for utilizing some default caching???*/
 			$cat_name = ! empty( $cats ) ? $cats[0] : '';/*@todo; if a listing is attached to multiple cats, we can print more than one cat later.*/
+			
+			/**
+			 * Prepare rest password link
+			 */
+			$login_page_id = get_directorist_option( 'user_login' );
```
Comment (obiPlabon) [inline includes/classes/class-email.php:114]: Use `directorist_get_page_id( 'login' )` instead.

File: includes/classes/class-email.php [hunk 2]
```diff
@@ -107,6 +107,24 @@ public function replace_in_content( $content, $order_id = 0, $listing_id = 0, $u
...
+
+			$query = parse_url($reset_password_url, PHP_URL_QUERY);
+			if ($query) {
+				$reset_password_url .= '&key='.$password_reset_key;
+			} else {
+				$reset_password_url .= '?key='.$password_reset_key;
+			}
+
+			$reset_password_url = $reset_password_url . '&user='. $user->user_email;
+
```
Comment (obiPlabon) [inline includes/classes/class-email.php:127]: Maybe we can refactor...
```php
$reset_password_url = add_query_arg( array( 
	'user' => $user->user_email,
	'key'   => get_password_reset_key( $user )
), $reset_password_url );
```

**Review by obiPlabon — CHANGES_REQUESTED** [review]

**Comment by obiPlabon** [comment]
image
image
image
image
image

https://monosnap.com/file/b73ut0tAbBThkt6COVN5qrXbYPCULX

image

**Review by obiPlabon — CHANGES_REQUESTED** [review]
Review has been shared.

File: includes/classes/class-user.php [hunk 3]
```diff
@@ -27,11 +27,247 @@ public function __construct() {
...
+		 *
+		 * @param \WP_Screen $current_screen Current WP_Screen object.
+		 */
+		public function action_current_screen(\WP_Screen $current_screen) : void {
+
+			if('users' !== $current_screen->base) {
+				return;
+			}
+
+			session_start();
```
Comment (obiPlabon) [inline includes/classes/class-user.php:121]: Instead of starting session here just to display admin messages we can follow the WP way and use query args to show admin messages. And you'll get the query args from the redirected URL. 

For example: _it's just an example, so don't just copy and paste._
```php
add_action('admin_notices', function() {
	if (!empty($_REQUEST['verification-request-sent-to'])) {
		$request_sent_to = (int) $_REQUEST['verification-request-sent-to'];
		printf('<div id="message" class="updated notice is-dismissable"><p>' . __('Email verification request sent to %d users.', 'directorist') . '</p></div>', $request_sent_to);
	}
});
```

File: templates/account/registration.php [hunk 4]
```diff
@@ -18,24 +18,26 @@
...
-								echo wp_kses_post( $output );
+								if(get_directorist_option('enable_email_verification')) {
+									$send_confirm_mail_url = add_query_arg([
+										'action' => 'send_confirmation_email',
+										'user'   => isset($_REQUEST['email']) ? $_REQUEST['email'] : '',
+										'directorist_nonce' => wp_create_nonce('directorist_nonce'),
+									], admin_url('admin-ajax.php'));
+
+									echo directorist_icon( 'las la-check', false ) . ' ' . __("Thank you for signing up! To complete the registration process, please verify your email address by clicking on the link we've sent to your email.", 'directorist');
+									echo "<span style='display:inline-block;margin-top:10px;'>" . sprintf(__("If you didn't receive the confirmation email, please check your spam folder. If you still can't find it, click on the %s to have a new email sent to you.", "directorist"), "<a href='" . $send_confirm_mail_url . "'>". __("Resend confirmation email")."</a>")."</span>";
```
Comment (obiPlabon) [inline templates/account/registration.php:33]: Same translation issue.

Comment (obiPlabon) [reply templates/account/registration.php:33]: Please follow translation best practices https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/

**Review by obiPlabon — CHANGES_REQUESTED** [review]

**Comment by obiPlabon** [comment]
Before:
image
After:
image
The lost password link loads the native password reset of WordPress, which breaks Directorist UX. please fix that.
